// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JetProtos.proto

package com.lzx.cloud.client.entity;

public final class PersonTestProtos {
  private PersonTestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jet.protobuf.PersonTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>bool sex = 3;</code>
     * @return The sex.
     */
    boolean getSex();

    /**
     * <code>int64 birthday = 4;</code>
     * @return The birthday.
     */
    long getBirthday();

    /**
     * <code>string address = 5;</code>
     * @return The address.
     */
    String getAddress();
    /**
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>repeated .jet.protobuf.Car cars = 6;</code>
     */
    java.util.List<Car>
        getCarsList();
    /**
     * <code>repeated .jet.protobuf.Car cars = 6;</code>
     */
    Car getCars(int index);
    /**
     * <code>repeated .jet.protobuf.Car cars = 6;</code>
     */
    int getCarsCount();
    /**
     * <code>repeated .jet.protobuf.Car cars = 6;</code>
     */
    java.util.List<? extends CarOrBuilder>
        getCarsOrBuilderList();
    /**
     * <code>repeated .jet.protobuf.Car cars = 6;</code>
     */
    CarOrBuilder getCarsOrBuilder(
        int index);

    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    int getOtherCount();
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    boolean containsOther(
        String key);
    /**
     * Use {@link #getOtherMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getOther();
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    java.util.Map<String, String>
    getOtherMap();
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */

    String getOtherOrDefault(
        String key,
        String defaultValue);
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */

    String getOtherOrThrow(
        String key);
  }
  /**
   * Protobuf type {@code jet.protobuf.PersonTest}
   */
  public static final class PersonTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jet.protobuf.PersonTest)
      PersonTestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PersonTest.newBuilder() to construct.
    private PersonTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PersonTest() {
      name_ = "";
      address_ = "";
      cars_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PersonTest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PersonTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 24: {

              sex_ = input.readBool();
              break;
            }
            case 32: {

              birthday_ = input.readInt64();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                cars_ = new java.util.ArrayList<Car>();
                mutable_bitField0_ |= 0x00000001;
              }
              cars_.add(
                  input.readMessage(Car.parser(), extensionRegistry));
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                other_ = com.google.protobuf.MapField.newMapField(
                    OtherDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<String, String>
              other__ = input.readMessage(
                  OtherDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              other_.getMutableMap().put(
                  other__.getKey(), other__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          cars_ = java.util.Collections.unmodifiableList(cars_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonTestProtos.internal_static_jet_protobuf_PersonTest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetOther();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonTestProtos.internal_static_jet_protobuf_PersonTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonTest.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @Override
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private boolean sex_;
    /**
     * <code>bool sex = 3;</code>
     * @return The sex.
     */
    @Override
    public boolean getSex() {
      return sex_;
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 4;
    private long birthday_;
    /**
     * <code>int64 birthday = 4;</code>
     * @return The birthday.
     */
    @Override
    public long getBirthday() {
      return birthday_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile Object address_;
    /**
     * <code>string address = 5;</code>
     * @return The address.
     */
    @Override
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    @Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARS_FIELD_NUMBER = 6;
    private java.util.List<Car> cars_;
    /**
     * <code>repeated .jet.protobuf.Car cars = 6;</code>
     */
    @Override
    public java.util.List<Car> getCarsList() {
      return cars_;
    }
    /**
     * <code>repeated .jet.protobuf.Car cars = 6;</code>
     */
    @Override
    public java.util.List<? extends CarOrBuilder>
        getCarsOrBuilderList() {
      return cars_;
    }
    /**
     * <code>repeated .jet.protobuf.Car cars = 6;</code>
     */
    @Override
    public int getCarsCount() {
      return cars_.size();
    }
    /**
     * <code>repeated .jet.protobuf.Car cars = 6;</code>
     */
    @Override
    public Car getCars(int index) {
      return cars_.get(index);
    }
    /**
     * <code>repeated .jet.protobuf.Car cars = 6;</code>
     */
    @Override
    public CarOrBuilder getCarsOrBuilder(
        int index) {
      return cars_.get(index);
    }

    public static final int OTHER_FIELD_NUMBER = 7;
    private static final class OtherDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  PersonTestProtos.internal_static_jet_protobuf_PersonTest_OtherEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> other_;
    private com.google.protobuf.MapField<String, String>
    internalGetOther() {
      if (other_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OtherDefaultEntryHolder.defaultEntry);
      }
      return other_;
    }

    public int getOtherCount() {
      return internalGetOther().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */

    @Override
    public boolean containsOther(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetOther().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOtherMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getOther() {
      return getOtherMap();
    }
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    @Override

    public java.util.Map<String, String> getOtherMap() {
      return internalGetOther().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    @Override

    public String getOtherOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetOther().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    @Override

    public String getOtherOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetOther().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (sex_ != false) {
        output.writeBool(3, sex_);
      }
      if (birthday_ != 0L) {
        output.writeInt64(4, birthday_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      for (int i = 0; i < cars_.size(); i++) {
        output.writeMessage(6, cars_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetOther(),
          OtherDefaultEntryHolder.defaultEntry,
          7);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (sex_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, sex_);
      }
      if (birthday_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, birthday_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      for (int i = 0; i < cars_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, cars_.get(i));
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetOther().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        other__ = OtherDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, other__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PersonTest)) {
        return super.equals(obj);
      }
      PersonTest other = (PersonTest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (getSex()
          != other.getSex()) return false;
      if (getBirthday()
          != other.getBirthday()) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getCarsList()
          .equals(other.getCarsList())) return false;
      if (!internalGetOther().equals(
          other.internalGetOther())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSex());
      hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBirthday());
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      if (getCarsCount() > 0) {
        hash = (37 * hash) + CARS_FIELD_NUMBER;
        hash = (53 * hash) + getCarsList().hashCode();
      }
      if (!internalGetOther().getMap().isEmpty()) {
        hash = (37 * hash) + OTHER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetOther().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PersonTest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonTest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PersonTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PersonTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PersonTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PersonTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PersonTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PersonTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jet.protobuf.PersonTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jet.protobuf.PersonTest)
        PersonTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonTestProtos.internal_static_jet_protobuf_PersonTest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetOther();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableOther();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonTestProtos.internal_static_jet_protobuf_PersonTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonTest.class, Builder.class);
      }

      // Construct using com.jet.protobuf.PersonTestProtos.PersonTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCarsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        sex_ = false;

        birthday_ = 0L;

        address_ = "";

        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          carsBuilder_.clear();
        }
        internalGetMutableOther().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonTestProtos.internal_static_jet_protobuf_PersonTest_descriptor;
      }

      @Override
      public PersonTest getDefaultInstanceForType() {
        return PersonTest.getDefaultInstance();
      }

      @Override
      public PersonTest build() {
        PersonTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PersonTest buildPartial() {
        PersonTest result = new PersonTest(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.age_ = age_;
        result.sex_ = sex_;
        result.birthday_ = birthday_;
        result.address_ = address_;
        if (carsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            cars_ = java.util.Collections.unmodifiableList(cars_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.cars_ = cars_;
        } else {
          result.cars_ = carsBuilder_.build();
        }
        result.other_ = internalGetOther();
        result.other_.makeImmutable();
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonTest) {
          return mergeFrom((PersonTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonTest other) {
        if (other == PersonTest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getSex() != false) {
          setSex(other.getSex());
        }
        if (other.getBirthday() != 0L) {
          setBirthday(other.getBirthday());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (carsBuilder_ == null) {
          if (!other.cars_.isEmpty()) {
            if (cars_.isEmpty()) {
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCarsIsMutable();
              cars_.addAll(other.cars_);
            }
            onChanged();
          }
        } else {
          if (!other.cars_.isEmpty()) {
            if (carsBuilder_.isEmpty()) {
              carsBuilder_.dispose();
              carsBuilder_ = null;
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000001);
              carsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCarsFieldBuilder() : null;
            } else {
              carsBuilder_.addAllMessages(other.cars_);
            }
          }
        }
        internalGetMutableOther().mergeFrom(
            other.internalGetOther());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonTest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {

        age_ = 0;
        onChanged();
        return this;
      }

      private boolean sex_ ;
      /**
       * <code>bool sex = 3;</code>
       * @return The sex.
       */
      @Override
      public boolean getSex() {
        return sex_;
      }
      /**
       * <code>bool sex = 3;</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(boolean value) {

        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool sex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {

        sex_ = false;
        onChanged();
        return this;
      }

      private long birthday_ ;
      /**
       * <code>int64 birthday = 4;</code>
       * @return The birthday.
       */
      @Override
      public long getBirthday() {
        return birthday_;
      }
      /**
       * <code>int64 birthday = 4;</code>
       * @param value The birthday to set.
       * @return This builder for chaining.
       */
      public Builder setBirthday(long value) {

        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 birthday = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBirthday() {

        birthday_ = 0L;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <code>string address = 5;</code>
       * @return The address.
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {

        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        address_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Car> cars_ =
        java.util.Collections.emptyList();
      private void ensureCarsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          cars_ = new java.util.ArrayList<Car>(cars_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Car, Car.Builder, CarOrBuilder> carsBuilder_;

      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public java.util.List<Car> getCarsList() {
        if (carsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cars_);
        } else {
          return carsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public int getCarsCount() {
        if (carsBuilder_ == null) {
          return cars_.size();
        } else {
          return carsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Car getCars(int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);
        } else {
          return carsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Builder setCars(
          int index, Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.set(index, value);
          onChanged();
        } else {
          carsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Builder setCars(
          int index, Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.set(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Builder addCars(Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(value);
          onChanged();
        } else {
          carsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Builder addCars(
          int index, Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(index, value);
          onChanged();
        } else {
          carsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Builder addCars(
          Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Builder addCars(
          int index, Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Builder addAllCars(
          Iterable<? extends Car> values) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cars_);
          onChanged();
        } else {
          carsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Builder clearCars() {
        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          carsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Builder removeCars(int index) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.remove(index);
          onChanged();
        } else {
          carsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Car.Builder getCarsBuilder(
          int index) {
        return getCarsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public CarOrBuilder getCarsOrBuilder(
          int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);  } else {
          return carsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public java.util.List<? extends CarOrBuilder>
           getCarsOrBuilderList() {
        if (carsBuilder_ != null) {
          return carsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cars_);
        }
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Car.Builder addCarsBuilder() {
        return getCarsFieldBuilder().addBuilder(
            Car.getDefaultInstance());
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public Car.Builder addCarsBuilder(
          int index) {
        return getCarsFieldBuilder().addBuilder(
            index, Car.getDefaultInstance());
      }
      /**
       * <code>repeated .jet.protobuf.Car cars = 6;</code>
       */
      public java.util.List<Car.Builder>
           getCarsBuilderList() {
        return getCarsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Car, Car.Builder, CarOrBuilder>
          getCarsFieldBuilder() {
        if (carsBuilder_ == null) {
          carsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Car, Car.Builder, CarOrBuilder>(
                  cars_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          cars_ = null;
        }
        return carsBuilder_;
      }

      private com.google.protobuf.MapField<
          String, String> other_;
      private com.google.protobuf.MapField<String, String>
      internalGetOther() {
        if (other_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              OtherDefaultEntryHolder.defaultEntry);
        }
        return other_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableOther() {
        onChanged();;
        if (other_ == null) {
          other_ = com.google.protobuf.MapField.newMapField(
              OtherDefaultEntryHolder.defaultEntry);
        }
        if (!other_.isMutable()) {
          other_ = other_.copy();
        }
        return other_;
      }

      public int getOtherCount() {
        return internalGetOther().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */

      @Override
      public boolean containsOther(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetOther().getMap().containsKey(key);
      }
      /**
       * Use {@link #getOtherMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, String> getOther() {
        return getOtherMap();
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      @Override

      public java.util.Map<String, String> getOtherMap() {
        return internalGetOther().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      @Override

      public String getOtherOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetOther().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      @Override

      public String getOtherOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetOther().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearOther() {
        internalGetMutableOther().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */

      public Builder removeOther(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableOther().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableOther() {
        return internalGetMutableOther().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      public Builder putOther(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableOther().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */

      public Builder putAllOther(
          java.util.Map<String, String> values) {
        internalGetMutableOther().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jet.protobuf.PersonTest)
    }

    // @@protoc_insertion_point(class_scope:jet.protobuf.PersonTest)
    private static final PersonTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PersonTest();
    }

    public static PersonTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PersonTest>
        PARSER = new com.google.protobuf.AbstractParser<PersonTest>() {
      @Override
      public PersonTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonTest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PersonTest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PersonTest> getParserForType() {
      return PARSER;
    }

    @Override
    public PersonTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jet.protobuf.Car)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string color = 2;</code>
     * @return The color.
     */
    String getColor();
    /**
     * <code>string color = 2;</code>
     * @return The bytes for color.
     */
    com.google.protobuf.ByteString
        getColorBytes();
  }
  /**
   * Protobuf type {@code jet.protobuf.Car}
   */
  public static final class Car extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jet.protobuf.Car)
      CarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Car() {
      name_ = "";
      color_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Car();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Car(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              color_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonTestProtos.internal_static_jet_protobuf_Car_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonTestProtos.internal_static_jet_protobuf_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Car.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 2;
    private volatile Object color_;
    /**
     * <code>string color = 2;</code>
     * @return The color.
     */
    @Override
    public String getColor() {
      Object ref = color_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        color_ = s;
        return s;
      }
    }
    /**
     * <code>string color = 2;</code>
     * @return The bytes for color.
     */
    @Override
    public com.google.protobuf.ByteString
        getColorBytes() {
      Object ref = color_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getColorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, color_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getColorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, color_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Car)) {
        return super.equals(obj);
      }
      Car other = (Car) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getColor()
          .equals(other.getColor())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Car parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Car parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Car prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jet.protobuf.Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jet.protobuf.Car)
        CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonTestProtos.internal_static_jet_protobuf_Car_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonTestProtos.internal_static_jet_protobuf_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Car.class, Builder.class);
      }

      // Construct using com.jet.protobuf.PersonTestProtos.Car.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        color_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonTestProtos.internal_static_jet_protobuf_Car_descriptor;
      }

      @Override
      public Car getDefaultInstanceForType() {
        return Car.getDefaultInstance();
      }

      @Override
      public Car build() {
        Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Car buildPartial() {
        Car result = new Car(this);
        result.name_ = name_;
        result.color_ = color_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Car) {
          return mergeFrom((Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Car other) {
        if (other == Car.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getColor().isEmpty()) {
          color_ = other.color_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Car parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Car) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object color_ = "";
      /**
       * <code>string color = 2;</code>
       * @return The color.
       */
      public String getColor() {
        Object ref = color_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          color_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string color = 2;</code>
       * @return The bytes for color.
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string color = 2;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string color = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        
        color_ = getDefaultInstance().getColor();
        onChanged();
        return this;
      }
      /**
       * <code>string color = 2;</code>
       * @param value The bytes for color to set.
       * @return This builder for chaining.
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        color_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jet.protobuf.Car)
    }

    // @@protoc_insertion_point(class_scope:jet.protobuf.Car)
    private static final Car DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Car();
    }

    public static Car getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Car>
        PARSER = new com.google.protobuf.AbstractParser<Car>() {
      @Override
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Car(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Car> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    @Override
    public Car getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jet_protobuf_PersonTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jet_protobuf_PersonTest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jet_protobuf_PersonTest_OtherEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jet_protobuf_PersonTest_OtherEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jet_protobuf_Car_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jet_protobuf_Car_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017JetProtos.proto\022\014jet.protobuf\"\332\001\n\nPers" +
      "onTest\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\013\n\003sex" +
      "\030\003 \001(\010\022\020\n\010birthday\030\004 \001(\003\022\017\n\007address\030\005 \001(" +
      "\t\022\037\n\004cars\030\006 \003(\0132\021.jet.protobuf.Car\0222\n\005ot" +
      "her\030\007 \003(\0132#.jet.protobuf.PersonTest.Othe" +
      "rEntry\032,\n\nOtherEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\t:\0028\001\"\"\n\003Car\022\014\n\004name\030\001 \001(\t\022\r\n\005col" +
      "or\030\002 \001(\tB$\n\020com.jet.protobufB\020PersonTest" +
      "Protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_jet_protobuf_PersonTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jet_protobuf_PersonTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jet_protobuf_PersonTest_descriptor,
        new String[] { "Name", "Age", "Sex", "Birthday", "Address", "Cars", "Other", });
    internal_static_jet_protobuf_PersonTest_OtherEntry_descriptor =
      internal_static_jet_protobuf_PersonTest_descriptor.getNestedTypes().get(0);
    internal_static_jet_protobuf_PersonTest_OtherEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jet_protobuf_PersonTest_OtherEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_jet_protobuf_Car_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jet_protobuf_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jet_protobuf_Car_descriptor,
        new String[] { "Name", "Color", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
