spring:
  profiles: eureka-server1
server:
  port: 8080                #指定该Eureka实例的端口
eureka:
  client:
    serviceurl:
      defaultZone: http://eureka-server2:8090/eureka/  #服务注册中心地址
#    registerWithEureka: false     #禁止注册自身
#    fetchRegistry: false          #因为该服务没有注册到其他注册中心，所以关闭从注册中心拉取服务列表。
#    #如果是服务注册中心集群，需要开启，开启就是去掉该配置，采用默认配置即可
#    serviceurl:
#      defaultZone: http://localhost:8090/eureka/  #服务注册中心地址
  server:
    renewalPercentThreshold: 0.49    #设置心跳正常的阀值，默认为1，测试时可以调低
  instance:
    hostname: eureka-server1
